config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'

  resources :events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  after_create :inscription_event_send
  def inscription_event_send
		AttendanceMailer.inscription_event(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
  validates :start_date, presence: true
	validates :duration, presence: true, :numericality => { :greater_than_or_equal_to => 0 }

	#le validate des méthodes est au singulier
	validate :multiple_of_5

	validates :title, presence: true, length: {minimum: 5, maximum: 140}
	validates :description, presence: true, length: {minimum: 20, maximum: 1000}
	validates :price, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 1000}
	validates :location, presence: true

	has_many :attendances
	has_many :users, through: :attendances
	belongs_to :admin, class_name: "User"

	def multiple_of_5
      if (self.duration % 5) != 0
      self.errors[:base] << "Number must be divisible by 5!"
      end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :first_name, presence: true, on: :update
  has_many :attendances, foreign_key: 'participant_id'
  has_many :events, through: :attendances

  #to make a difference between the users who organise events and the users who participate only
	has_many :organisers, foreign_key: 'admin_id', class_name: "Event"

  after_create :send_welcome
  def send_welcome
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  # GET /attendances
  # GET /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances
  # POST /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance, notice: 'Attendance was successfully created.' }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url, notice: 'Attendance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attendance_params
      params.require(:attendance).permit(:strupe_customer_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  def index
  end

  def new
  	@event = Event.new
  end

  def create
 		@event = Event.new('start_date' => params[:start_date],
                  			 'duration' => params[:duration],
                  			  'title' => params[:title],
                  			   'description' => params[:description],
                  			    'price' => params[:price],
                  			     'location' => params[:location])
    @event.admin_id = current_user.id
   		if @event.save # essaie de sauvegarder en base
     		 flash[:success] = "Nouvel événement bien créé !"
         render 'events/index'
	    else
   		   render "new"
    	end
  end

  def show
  	@event = Event.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user=User.find(params[:id])
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class = "jumbotron"style="background-image: url(https://images.pexels.com/photos/3536252/pexels-photo-3536252.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940)">
<div class="pl-5" style="height: 300px;">
  <h1 class="display-3" style="color:white">Bienvenue sur Event Brite Light</h1>
		<h4 class="lead" style="color:white">Le site de réservation de tes plus folles soirées !</h4>
		<br>
			<h6 style="color:white">Si tu es organisateur d'événements, tu peux en créer un <a> <%= link_to "ici !", new_event_path %> </a> </h6>
</div>


 <% if flash[:success] %>
      <div class="alert alert-success" role="alert"><%= flash[:success] %></div>
 <% elsif flash[:danger] %>
      <div class="alert alert-danger" role="alert"><%= flash[:danger] %></div>
   <% end %>

    <h4 class="h1-responsive font-weight-bold my-5 pl-5">Quelques événements dans ta ville...</h4>


<section>

<div class="card-deck">
<%Event.all.each do |event|%>
<div class="col-sm-4 mb-3">
<div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
  <div class="card-header h4">
    <%=event.title%>
  </div>
  <div class="card-body align-center">
      <p><%=event.start_date%></p>
      <p><%=event.location%></p>
      <footer class="blockquote-footer">
      <div class="row justify-content-between align-self-center mx-3">
        <p><%=event.price%> €</p>
        <a class="btn btn-outline-secondary" <%= link_to "Voir plus", event_path(event.id)%></a>
      </div>
      </footer>
  </div>
</div>
</div>
<%end%>
</div>
</section>

app/views/events/new.html.erb
<h2 class="h1-responsive font-weight-bold my-5 pl-5">Page de création d'un nouvel événement</h2>


<body>

   <div class=" border border-light p-5">

        <% if flash[:danger] %>
          <div class="alert alert-danger" role="alert"><%= flash[:danger] %></div>
        <% end %>


     <p class="h4 mb-4">Pour créer un nouvel événement, remplissez le formulaire ci-dessous :</p>

        <%= form_tag url_for(action: 'create'), method: "post" do %>

        <p><%= label_tag 'Date de début :' %></p>
        <%= text_field_tag 'start_date', nil, class: "form-control mb-4" %>

        <p><%= label_tag 'Durée :' %></p>
        <%= text_field_tag 'duration', nil,  class: "form-control mb-2"%>

        <p><%= label_tag 'Titre :' %></p>
        <%= text_field_tag 'title', nil,  class: "form-control mb-2"%>

        <p><%= label_tag 'Description :' %></p>
        <%= text_field_tag 'description', nil,  class: "form-control mb-2"%>

        <p><%= label_tag 'Prix :' %></p>
        <%= text_field_tag 'price', nil,  class: "form-control mb-2"%>

        <p><%= label_tag 'Ville :' %></p>
        <%= text_field_tag 'location', nil,  class: "form-control mb-2"%>

            </br>

        <%= submit_tag "Créer l'évent", class: "btn btn-info btn-block" %>

      <% end %>
    </div>


</body>

app/views/events/show.html.erb
<div class="pl-5">
<h2 class="h1-responsive font-weight-bold my-5">Bienvenue sur la page de l'event n°<%= @event.id %></h2>

   <div class="my-3 p-3 bg-white rounded box-shadow text-success">


       <div class="media text-dark pt-3">
         <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
           <strong class="d-block text-gray-dark">TITRE</strong>
           <%= @event.title%>
         </p>
       </div>

       <div class="media text-dark pt-3">
         <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
           <strong class="d-block text-gray-dark">DESCRIPTION</strong>
           <%= @event.description%>
         </p>
       </div>

       <div class="media text-dark pt-3">
         <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
           <strong class="d-block text-gray-dark">DATE</strong>
             <a> <%= @event.start_date %> </a>
         </p>
       </div>

        <div class="media text-dark pt-3">
         <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
           <strong class="d-block text-gray-dark">DUREE</strong>
           <a> <%= @event.duration %> minutes </a>
         </p>
       </div>

        <div class="media text-dark pt-3">
         <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
           <strong class="d-block text-gray-dark">PRICE</strong>
           <a> <%= @event.price %>€ </a>
         </p>
       </div>

        <div class="media text-dark pt-3">
         <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
           <strong class="d-block text-gray-dark">LOCATION</strong>
           <a> <%= @event.location %> </a>
         </p>
       </div>

       <div class="media text-dark pt-3">
         <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
           <strong class="d-block text-gray-dark">ORGANISATEUR</strong>
           <a> <%= @event.admin.first_name %> <%= @event.admin.last_name %></a>
         </p>
       </div>

     </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Bootswatch SUPERHERO-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/flatly/bootstrap.min.css" integrity="sha384-qF/QmIAj5ZaYFAeQcrQ6bfVMAh4zZlrGwTPY7T/M+iTTLJqJBJjwwnsE5Y0mV7QK" crossorigin="anonymous">

    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

      <!-- Navigation bar-->

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/events">Event Brite Light</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="true" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
       <div class="navbar-collapse collapse show" id="navbarColor03" style="">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" <%= link_to "Accueil", root_path %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" <%= link_to "Créer un événement", new_event_path %></a>
            </li>
          </ul>



      <%if user_signed_in?%>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:black">
            <%= current_user.email %>
          </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" <%= link_to "Mon profil", user_path(current_user.id) %></a>
              <a class="dropdown-item" <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></a>
            </div>
        </div>


        <%else%>

        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            S'inscrire / Se conntecter
          </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" <%= link_to "S'inscrire", new_user_registration_path %></a>
              <a class="dropdown-item" <%= link_to "Se connecter", new_user_session_path %></a>
            </div>
        </div>

        <%end%>


    </nav>
    <% if flash[:error].present? %>
          <p class='flash-error alert-danger'><%= flash[:error] %></p>
        <% end %>
        <% if flash[:notice].present? %>
          <div class="alert alert-dismissible alert-success">
            <button type="button" class="close disabled" data-dismiss="alert">&times;</button>
            <p class='flash-notice alert-success alert-heading disabled'><br><%= flash[:notice] %></p>
          </div>
        <% end %>

    <%= yield %>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/users/edit.html.erb
<div class="pl-5">
<h2 class="h1-responsive font-weight-bold my-5">Editer ton profil</h2>
</div>

app/views/users/show.html.erb
<div class="pl-5">
<h2 class="h1-responsive font-weight-bold my-5">Bienvenue sur ton profil <%= @user.first_name %></h2>


	<div class="my-3 p-3 bg-white rounded box-shadow text-success">


        <div class="media text-dark pt-3">
          <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">PRENOM</strong>
            <%= @user.first_name%>
          </p>
        </div>

        <div class="media text-dark pt-3">
          <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">NOM</strong>
            <%= @user.last_name%>
          </p>
        </div>


         <div class="media text-dark pt-3">
          <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">DESCRIPTION</strong>
            <%= @user.description%>
          </p>

        </div> <div class="media text-dark pt-3">
          <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">EMAIL</strong>
            <%= @user.email%>
          </p>
        </div>
				<br>
				<%= link_to "Editer ton profil", edit_user_path %> <br><br>
				<%= link_to "Editer tes informations sur ton compte", edit_user_registration_path %>
   </div>


</br></br></br>

  <% if Event.find_by(admin_id: @user.id) %>

  <h4>Tes événements :</h4>
</br>

<section>
<div class="card-deck">
<%Event.all.each do |event|%>
<%if event.admin_id == @user.id%>
<div class="col-sm-4 mb-3">
<div class="card">
  <div class="card-header">
    Event #<%=event.id%>
  </div>
  <div class="card-body align-center">
    <blockquote class="blockquote mb-0">
      <p><%=event.title%></p>
      <footer class="blockquote-footer">
      <div class="row justify-content-between align-self-center mx-3">
        <p><%=event.start_date%></p>
       </div>
      </footer>
    </blockquote>
  </div>
</div>
</div>
<%end%>
<%end%>
</div>
</section>

  <% else %>

    <h4>Tu n'as pas encore crée d'événement</h4>

 <% end %>
 </div>